{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fmodern Consolas;}{\f1\fmodern\fcharset0 Consolas;}{\f2\fnil\fcharset129 Courier New;}}
{\colortbl ;\red20\green20\blue20;\red142\green142\blue142;\red16\green158\blue98;\red148\green146\blue12;\red170\green51\blue170;\red170\green64\blue64;\red56\green136\blue159;\red18\green124\blue155;\red126\green126\blue12;\red12\green100\blue126;\red9\green118\blue72;\red85\green85\blue85;\red94\green147\blue162;\red18\green18\blue18;\red245\green245\blue245;\red170\green85\blue85;}
\viewkind4\uc1\pard\f0\fs20 Authenticating with public key "Imported-Openssh-Key"\cf1\highlight2 
\par \cf0\highlight0     \u9484?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9488?\cf1\highlight2 
\par \cf0\highlight0     \u9474?                 \cf3\f1\bullet  MobaXterm Personal Edition v24.2 \bullet\cf0\f0                  \u9474?\cf1\highlight2 
\par \cf0\highlight0     \u9474?               \cf4 (SSH client, X server and network tools)\cf0                \u9474?\cf1\highlight2 
\par \cf0\highlight0     \u9474?                                                                      \u9474?\cf1\highlight2 
\par \cf0\highlight0     \u9474? \u11166? SSH session to \cf5 ec2-user@13.60.104.229                    \cf0           \u9474?\cf1\highlight2 
\par \cf0\highlight0     \u9474?\f1    \bullet  Direct SSH      :  \cf3\f0\u10003?\cf0                                              \u9474?\cf1\highlight2 
\par \cf0\highlight0     \u9474?\f1    \bullet  SSH compression :  \cf3\f0\u10003?\cf0                                              \u9474?\cf1\highlight2 
\par \cf0\highlight0     \u9474?\f1    \bullet  SSH-browser     :  \cf3\f0\u10003?\cf0                                              \u9474?\cf1\highlight2 
\par \cf0\highlight0     \u9474?\f1    \bullet  X11-forwarding  :  \cf6\f0\u10007?\cf0   (disabled or not supported by server)      \u9474?\cf1\highlight2 
\par \cf0\highlight0     \u9474?                                                                      \u9474?\cf1\highlight2 
\par \cf0\highlight0     \u9474? \u11166? For more info, ctrl+click on \cf7\ul help\cf0\ulnone  or visit our \cf7\ul website\cf0\ulnone .            \u9474?\cf1\highlight2 
\par \cf0\highlight0     \u9492?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9472?\u9496?\cf1\highlight2 
\par 
\par \cf0\highlight0    ,     #_\cf1\highlight2 
\par \cf0\highlight0    ~\\_  ####_        Amazon Linux 2023\cf1\highlight2 
\par \cf0\highlight0   ~~  \\_#####\\\cf1\highlight2 
\par \cf0\highlight0   ~~     \\###|\cf1\highlight2 
\par \cf0\highlight0   ~~       \\#/ ___   https://aws.amazon.com/linux/amazon-linux-2023\cf1\highlight2 
\par \cf0\highlight0    ~~       V~' '->\cf1\highlight2 
\par \cf0\highlight0     ~~~         /\cf1\highlight2 
\par \cf0\highlight0       ~~._.   _/\cf1\highlight2 
\par \cf0\highlight0          _/ _/\cf1\highlight2 
\par \cf0\highlight0        _/m/'\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ sudo apt-get update\cf1\highlight2 
\par \cf0\highlight0 sudo: apt-get: command not found\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ ^C\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ sudo yum update\cf1\highlight2 
\par \cf0\highlight0 Last metadata expiration check: 2:13:01 ago on Wed Aug 14 07:56:54 2024.\cf1\highlight2 
\par \cf0\highlight0 Dependencies resolved.\cf1\highlight2 
\par \cf0\highlight0 Nothing to do.\cf1\highlight2 
\par \cf0\highlight0 Complete!\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ sudo yum install -y nodejs npm\cf1\highlight2 
\par \cf0\highlight0 Last metadata expiration check: 2:13:44 ago on Wed Aug 14 07:56:54 2024.\cf1\highlight2 
\par \cf0\highlight0 Dependencies resolved.\cf1\highlight2 
\par \cf0\highlight0 ======================================================================================\cf1\highlight2 
\par \cf0\highlight0  Package            Arch     Version                              Repository     Size\cf1\highlight2 
\par \cf0\highlight0 ======================================================================================\cf1\highlight2 
\par \cf0\highlight0 Installing:\cf1\highlight2 
\par \cf0\highlight0  \cf3 nodejs            \cf0  x86_64   1:18.20.2-1.amzn2023.0.1             amazonlinux    13 M\cf1\highlight2 
\par \cf0\highlight0  \cf3 nodejs-npm        \cf0  x86_64   1:10.5.0-1.18.20.2.1.amzn2023.0.1    amazonlinux   1.9 M\cf1\highlight2 
\par \cf0\highlight0 Installing dependencies:\cf1\highlight2 
\par \cf0\highlight0  \cf3 libbrotli         \cf0  x86_64   1.0.9-4.amzn2023.0.2                 amazonlinux   315 k\cf1\highlight2 
\par \cf0\highlight0  \cf3 nodejs-libs       \cf0  x86_64   1:18.20.2-1.amzn2023.0.1             amazonlinux    14 M\cf1\highlight2 
\par \cf0\highlight0 Installing weak dependencies:\cf1\highlight2 
\par \cf0\highlight0  \cf3 nodejs-docs       \cf0  noarch   1:18.20.2-1.amzn2023.0.1             amazonlinux   7.8 M\cf1\highlight2 
\par \cf0\highlight0  \cf3 nodejs-full-i18n  \cf0  x86_64   1:18.20.2-1.amzn2023.0.1             amazonlinux   8.4 M\cf1\highlight2 
\par 
\par \cf0\highlight0 Transaction Summary\cf1\highlight2 
\par \cf0\highlight0 ======================================================================================\cf1\highlight2 
\par \cf0\highlight0 Install  6 Packages\cf1\highlight2 
\par 
\par \cf0\highlight0 Total download size: 45 M\cf1\highlight2 
\par \cf0\highlight0 Installed size: 224 M\cf1\highlight2 
\par \cf0\highlight0 Downloading Packages:\cf1\highlight2 
\par \cf0\highlight0 (1/6): libbrotli-1.0.9-4.amzn2023.0.2.x86_64.rpm      3.8 MB/s | 315 kB     00:00\cf1\highlight2 
\par \cf0\highlight0 (2/6): nodejs-docs-18.20.2-1.amzn2023.0.1.noarch.rpm   35 MB/s | 7.8 MB     00:00\cf1\highlight2 
\par \cf0\highlight0 (3/6): nodejs-18.20.2-1.amzn2023.0.1.x86_64.rpm        33 MB/s |  13 MB     00:00\cf1\highlight2 
\par \cf0\highlight0 (4/6): nodejs-full-i18n-18.20.2-1.amzn2023.0.1.x86_64  22 MB/s | 8.4 MB     00:00\cf1\highlight2 
\par \cf0\highlight0 (5/6): nodejs-npm-10.5.0-1.18.20.2.1.amzn2023.0.1.x86  21 MB/s | 1.9 MB     00:00\cf1\highlight2 
\par \cf0\highlight0 (6/6): nodejs-libs-18.20.2-1.amzn2023.0.1.x86_64.rpm   36 MB/s |  14 MB     00:00\cf1\highlight2 
\par \cf0\highlight0 --------------------------------------------------------------------------------------\cf1\highlight2 
\par \cf0\highlight0 Total                                                  66 MB/s |  45 MB     00:00\cf1\highlight2 
\par \cf0\highlight0 Running transaction check\cf1\highlight2 
\par \cf0\highlight0 Transaction check succeeded.\cf1\highlight2 
\par \cf0\highlight0 Running transaction test\cf1\highlight2 
\par \cf0\highlight0 Transaction test succeeded.\cf1\highlight2 
\par \cf0\highlight0 Running transaction\cf1\highlight2 
\par \cf0\highlight0   Running scriptlet: nodejs-1:18.20.2-1.amzn2023.0.1.x86_64                       1/1\cf1\highlight2 
\par \cf0\highlight0   Preparing        :                                                              1/1\cf1\highlight2 
\par \cf0\highlight0   Installing       : nodejs-docs-1:18.20.2-1.amzn2023.0.1.noarch                  1/6\cf1\highlight2 
\par \cf0\highlight0   Installing       : libbrotli-1.0.9-4.amzn2023.0.2.x86_64                        2/6\cf1\highlight2 
\par \cf0\highlight0   Installing       : nodejs-libs-1:18.20.2-1.amzn2023.0.1.x86_64                  3/6\cf1\highlight2 
\par \cf0\highlight0   Installing       : nodejs-full-i18n-1:18.20.2-1.amzn2023.0.1.x86_64             4/6\cf1\highlight2 
\par \cf0\highlight0   Installing       : nodejs-npm-1:10.5.0-1.18.20.2.1.amzn2023.0.1.x86_64          5/6\cf1\highlight2 
\par \cf0\highlight0   Installing       : nodejs-1:18.20.2-1.amzn2023.0.1.x86_64                       6/6\cf1\highlight2 
\par \cf0\highlight0   Running scriptlet: nodejs-1:18.20.2-1.amzn2023.0.1.x86_64                       6/6\cf1\highlight2 
\par \cf0\highlight0   Verifying        : libbrotli-1.0.9-4.amzn2023.0.2.x86_64                        1/6\cf1\highlight2 
\par \cf0\highlight0   Verifying        : nodejs-1:18.20.2-1.amzn2023.0.1.x86_64                       2/6\cf1\highlight2 
\par \cf0\highlight0   Verifying        : nodejs-docs-1:18.20.2-1.amzn2023.0.1.noarch                  3/6\cf1\highlight2 
\par \cf0\highlight0   Verifying        : nodejs-full-i18n-1:18.20.2-1.amzn2023.0.1.x86_64             4/6\cf1\highlight2 
\par \cf0\highlight0   Verifying        : nodejs-libs-1:18.20.2-1.amzn2023.0.1.x86_64                  5/6\cf1\highlight2 
\par \cf0\highlight0   Verifying        : nodejs-npm-1:10.5.0-1.18.20.2.1.amzn2023.0.1.x86_64          6/6\cf1\highlight2 
\par 
\par \cf0\highlight0 Installed:\cf1\highlight2 
\par \cf0\highlight0   libbrotli-1.0.9-4.amzn2023.0.2.x86_64\cf1\highlight2 
\par \cf0\highlight0   nodejs-1:18.20.2-1.amzn2023.0.1.x86_64\cf1\highlight2 
\par \cf0\highlight0   nodejs-docs-1:18.20.2-1.amzn2023.0.1.noarch\cf1\highlight2 
\par \cf0\highlight0   nodejs-full-i18n-1:18.20.2-1.amzn2023.0.1.x86_64\cf1\highlight2 
\par \cf0\highlight0   nodejs-libs-1:18.20.2-1.amzn2023.0.1.x86_64\cf1\highlight2 
\par \cf0\highlight0   nodejs-npm-1:10.5.0-1.18.20.2.1.amzn2023.0.1.x86_64\cf1\highlight2 
\par 
\par \cf0\highlight0 Complete!\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ sudo yum install -y python3-pip python3-dev\cf1\highlight2 
\par \cf0\highlight0 Last metadata expiration check: 2:14:13 ago on Wed Aug 14 07:56:54 2024.\cf1\highlight2 
\par \cf0\highlight0 No match for argument: \b python3-dev\cf1\highlight2\b0 
\par \cf0\highlight0 Error: Unable to find a match: python3-dev\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ ^C\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ sudo yum install -y python3-pip python3-devel\cf1\highlight2 
\par \cf0\highlight0 Last metadata expiration check: 2:14:56 ago on Wed Aug 14 07:56:54 2024.\cf1\highlight2 
\par \cf0\highlight0 Dependencies resolved.\cf1\highlight2 
\par \cf0\highlight0 ======================================================================================\cf1\highlight2 
\par \cf0\highlight0  Package               Arch        Version                     Repository        Size\cf1\highlight2 
\par \cf0\highlight0 ======================================================================================\cf1\highlight2 
\par \cf0\highlight0 Installing:\cf1\highlight2 
\par \cf0\highlight0  \cf3 python3-devel        \cf0  x86_64      3.9.16-1.amzn2023.0.9       amazonlinux      205 k\cf1\highlight2 
\par \cf0\highlight0  \cf3 python3-pip          \cf0  noarch      21.3.1-2.amzn2023.0.7       amazonlinux      1.8 M\cf1\highlight2 
\par \cf0\highlight0 Installing weak dependencies:\cf1\highlight2 
\par \cf0\highlight0  \cf3 libxcrypt-compat     \cf0  x86_64      4.4.33-7.amzn2023           amazonlinux       92 k\cf1\highlight2 
\par 
\par \cf0\highlight0 Transaction Summary\cf1\highlight2 
\par \cf0\highlight0 ======================================================================================\cf1\highlight2 
\par \cf0\highlight0 Install  3 Packages\cf1\highlight2 
\par 
\par \cf0\highlight0 Total download size: 2.1 M\cf1\highlight2 
\par \cf0\highlight0 Installed size: 12 M\cf1\highlight2 
\par \cf0\highlight0 Downloading Packages:\cf1\highlight2 
\par \cf0\highlight0 (1/3): python3-pip-21.3.1-2.amzn2023.0.7.noarch.rpm    21 MB/s | 1.8 MB     00:00\cf1\highlight2 
\par \cf0\highlight0 (2/3): libxcrypt-compat-4.4.33-7.amzn2023.x86_64.rpm  1.0 MB/s |  92 kB     00:00\cf1\highlight2 
\par \cf0\highlight0 (3/3): python3-devel-3.9.16-1.amzn2023.0.9.x86_64.rpm 1.6 MB/s | 205 kB     00:00\cf1\highlight2 
\par \cf0\highlight0 --------------------------------------------------------------------------------------\cf1\highlight2 
\par \cf0\highlight0 Total                                                  11 MB/s | 2.1 MB     00:00\cf1\highlight2 
\par \cf0\highlight0 Running transaction check\cf1\highlight2 
\par \cf0\highlight0 Transaction check succeeded.\cf1\highlight2 
\par \cf0\highlight0 Running transaction test\cf1\highlight2 
\par \cf0\highlight0 Transaction test succeeded.\cf1\highlight2 
\par \cf0\highlight0 Running transaction\cf1\highlight2 
\par \cf0\highlight0   Preparing        :                                                              1/1\cf1\highlight2 
\par \cf0\highlight0   Installing       : libxcrypt-compat-4.4.33-7.amzn2023.x86_64                    1/3\cf1\highlight2 
\par \cf0\highlight0   Installing       : python3-pip-21.3.1-2.amzn2023.0.7.noarch                     2/3\cf1\highlight2 
\par \cf0\highlight0   Installing       : python3-devel-3.9.16-1.amzn2023.0.9.x86_64                   3/3\cf1\highlight2 
\par \cf0\highlight0   Running scriptlet: python3-devel-3.9.16-1.amzn2023.0.9.x86_64                   3/3\cf1\highlight2 
\par \cf0\highlight0   Verifying        : libxcrypt-compat-4.4.33-7.amzn2023.x86_64                    1/3\cf1\highlight2 
\par \cf0\highlight0   Verifying        : python3-devel-3.9.16-1.amzn2023.0.9.x86_64                   2/3\cf1\highlight2 
\par \cf0\highlight0   Verifying        : python3-pip-21.3.1-2.amzn2023.0.7.noarch                     3/3\cf1\highlight2 
\par 
\par \cf0\highlight0 Installed:\cf1\highlight2 
\par \cf0\highlight0   libxcrypt-compat-4.4.33-7.amzn2023.x86_64\cf1\highlight2 
\par \cf0\highlight0   python3-devel-3.9.16-1.amzn2023.0.9.x86_64\cf1\highlight2 
\par \cf0\highlight0   python3-pip-21.3.1-2.amzn2023.0.7.noarch\cf1\highlight2 
\par 
\par \cf0\highlight0 Complete!\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ sudo yum install sqlite3\cf1\highlight2 
\par \cf0\highlight0 Last metadata expiration check: 2:16:19 ago on Wed Aug 14 07:56:54 2024.\cf1\highlight2 
\par \cf0\highlight0 No match for argument: \b sqlite3\cf1\highlight2\b0 
\par \cf0\highlight0 Error: Unable to find a match: sqlite3\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ ^C\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ sudo sqlite3 --version\cf1\highlight2 
\par \cf0\highlight0 sudo: sqlite3: command not found\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ sqlite3 --version\cf1\highlight2 
\par \cf0\highlight0 -bash: sqlite3: command not found\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ sudo yum install sqlite-devel\cf1\highlight2 
\par \cf0\highlight0 Last metadata expiration check: 2:17:17 ago on Wed Aug 14 07:56:54 2024.\cf1\highlight2 
\par \cf0\highlight0 Dependencies resolved.\cf1\highlight2 
\par \cf0\highlight0 ======================================================================================\cf1\highlight2 
\par \cf0\highlight0  Package            Architecture Version                      Repository         Size\cf1\highlight2 
\par \cf0\highlight0 ======================================================================================\cf1\highlight2 
\par \cf0\highlight0 Installing:\cf1\highlight2 
\par \cf0\highlight0  \cf3 sqlite-devel      \cf0  x86_64       3.40.0-1.amzn2023.0.4        amazonlinux       143 k\cf1\highlight2 
\par \cf0\highlight0 Installing dependencies:\cf1\highlight2 
\par \cf0\highlight0  \cf3 sqlite            \cf0  x86_64       3.40.0-1.amzn2023.0.4        amazonlinux       808 k\cf1\highlight2 
\par 
\par \cf0\highlight0 Transaction Summary\cf1\highlight2 
\par \cf0\highlight0 ======================================================================================\cf1\highlight2 
\par \cf0\highlight0 Install  2 Packages\cf1\highlight2 
\par 
\par \cf0\highlight0 Total download size: 951 k\cf1\highlight2 
\par \cf0\highlight0 Installed size: 2.3 M\cf1\highlight2 
\par \cf0\highlight0 Is this ok [y/N]: y\cf1\highlight2 
\par \cf0\highlight0 Downloading Packages:\cf1\highlight2 
\par \cf0\highlight0 (1/2): sqlite-3.40.0-1.amzn2023.0.4.x86_64.rpm        8.5 MB/s | 808 kB     00:00\cf1\highlight2 
\par \cf0\highlight0 (2/2): sqlite-devel-3.40.0-1.amzn2023.0.4.x86_64.rpm  1.4 MB/s | 143 kB     00:00\cf1\highlight2 
\par \cf0\highlight0 --------------------------------------------------------------------------------------\cf1\highlight2 
\par \cf0\highlight0 Total                                                 6.4 MB/s | 951 kB     00:00\cf1\highlight2 
\par \cf0\highlight0 Running transaction check\cf1\highlight2 
\par \cf0\highlight0 Transaction check succeeded.\cf1\highlight2 
\par \cf0\highlight0 Running transaction test\cf1\highlight2 
\par \cf0\highlight0 Transaction test succeeded.\cf1\highlight2 
\par \cf0\highlight0 Running transaction\cf1\highlight2 
\par \cf0\highlight0   Preparing        :                                                              1/1\cf1\highlight2 
\par \cf0\highlight0   Installing       : sqlite-3.40.0-1.amzn2023.0.4.x86_64                          1/2\cf1\highlight2 
\par \cf0\highlight0   Installing       : sqlite-devel-3.40.0-1.amzn2023.0.4.x86_64                    2/2\cf1\highlight2 
\par \cf0\highlight0   Running scriptlet: sqlite-devel-3.40.0-1.amzn2023.0.4.x86_64                    2/2\cf1\highlight2 
\par \cf0\highlight0   Verifying        : sqlite-3.40.0-1.amzn2023.0.4.x86_64                          1/2\cf1\highlight2 
\par \cf0\highlight0   Verifying        : sqlite-devel-3.40.0-1.amzn2023.0.4.x86_64                    2/2\cf1\highlight2 
\par 
\par \cf0\highlight0 Installed:\cf1\highlight2 
\par \cf0\highlight0   sqlite-3.40.0-1.amzn2023.0.4.x86_64    sqlite-devel-3.40.0-1.amzn2023.0.4.x86_64\cf1\highlight2 
\par 
\par \cf0\highlight0 Complete!\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ ^C\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ ^C\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ sudo yum install git\cf1\highlight2 
\par \cf0\highlight0 Last metadata expiration check: 2:19:08 ago on Wed Aug 14 07:56:54 2024.\cf1\highlight2 
\par \cf0\highlight0 Dependencies resolved.\cf1\highlight2 
\par \cf0\highlight0 ======================================================================================\cf1\highlight2 
\par \cf0\highlight0  Package              Arch       Version                        Repository       Size\cf1\highlight2 
\par \cf0\highlight0 ======================================================================================\cf1\highlight2 
\par \cf0\highlight0 Installing:\cf1\highlight2 
\par \cf0\highlight0  \cf3 git                 \cf0  x86_64     2.40.1-1.amzn2023.0.3          amazonlinux      54 k\cf1\highlight2 
\par \cf0\highlight0 Installing dependencies:\cf1\highlight2 
\par \cf0\highlight0  \cf3 git-core            \cf0  x86_64     2.40.1-1.amzn2023.0.3          amazonlinux     4.3 M\cf1\highlight2 
\par \cf0\highlight0  \cf3 git-core-doc        \cf0  noarch     2.40.1-1.amzn2023.0.3          amazonlinux     2.6 M\cf1\highlight2 
\par \cf0\highlight0  \cf3 perl-Error          \cf0  noarch     1:0.17029-5.amzn2023.0.2       amazonlinux      41 k\cf1\highlight2 
\par \cf0\highlight0  \cf3 perl-File-Find      \cf0  noarch     1.37-477.amzn2023.0.6          amazonlinux      26 k\cf1\highlight2 
\par \cf0\highlight0  \cf3 perl-Git            \cf0  noarch     2.40.1-1.amzn2023.0.3          amazonlinux      42 k\cf1\highlight2 
\par \cf0\highlight0  \cf3 perl-TermReadKey    \cf0  x86_64     2.38-9.amzn2023.0.2            amazonlinux      36 k\cf1\highlight2 
\par \cf0\highlight0  \cf3 perl-lib            \cf0  x86_64     0.65-477.amzn2023.0.6          amazonlinux      15 k\cf1\highlight2 
\par 
\par \cf0\highlight0 Transaction Summary\cf1\highlight2 
\par \cf0\highlight0 ======================================================================================\cf1\highlight2 
\par \cf0\highlight0 Install  8 Packages\cf1\highlight2 
\par 
\par \cf0\highlight0 Total download size: 7.1 M\cf1\highlight2 
\par \cf0\highlight0 Installed size: 34 M\cf1\highlight2 
\par \cf0\highlight0 Is this ok [y/N]: y\cf1\highlight2 
\par \cf0\highlight0 Downloading Packages:\cf1\highlight2 
\par \cf0\highlight0 (1/8): git-2.40.1-1.amzn2023.0.3.x86_64.rpm           1.0 MB/s |  54 kB     00:00\cf1\highlight2 
\par \cf0\highlight0 (2/8): git-core-doc-2.40.1-1.amzn2023.0.3.noarch.rpm   31 MB/s | 2.6 MB     00:00\cf1\highlight2 
\par \cf0\highlight0 (3/8): perl-Error-0.17029-5.amzn2023.0.2.noarch.rpm   1.1 MB/s |  41 kB     00:00\cf1\highlight2 
\par \cf0\highlight0 (4/8): git-core-2.40.1-1.amzn2023.0.3.x86_64.rpm       38 MB/s | 4.3 MB     00:00\cf1\highlight2 
\par \cf0\highlight0 (5/8): perl-File-Find-1.37-477.amzn2023.0.6.noarch.rp 883 kB/s |  26 kB     00:00\cf1\highlight2 
\par \cf0\highlight0 (6/8): perl-TermReadKey-2.38-9.amzn2023.0.2.x86_64.rp 1.9 MB/s |  36 kB     00:00\cf1\highlight2 
\par \cf0\highlight0 (7/8): perl-Git-2.40.1-1.amzn2023.0.3.noarch.rpm      948 kB/s |  42 kB     00:00\cf1\highlight2 
\par \cf0\highlight0 (8/8): perl-lib-0.65-477.amzn2023.0.6.x86_64.rpm      784 kB/s |  15 kB     00:00\cf1\highlight2 
\par \cf0\highlight0 --------------------------------------------------------------------------------------\cf1\highlight2 
\par \cf0\highlight0 Total                                                  37 MB/s | 7.1 MB     00:00\cf1\highlight2 
\par \cf0\highlight0 Running transaction check\cf1\highlight2 
\par \cf0\highlight0 Transaction check succeeded.\cf1\highlight2 
\par \cf0\highlight0 Running transaction test\cf1\highlight2 
\par \cf0\highlight0 Transaction test succeeded.\cf1\highlight2 
\par \cf0\highlight0 Running transaction\cf1\highlight2 
\par \cf0\highlight0   Preparing        :                                                              1/1\cf1\highlight2 
\par \cf0\highlight0   Installing       : git-core-2.40.1-1.amzn2023.0.3.x86_64                        1/8\cf1\highlight2 
\par \cf0\highlight0   Installing       : git-core-doc-2.40.1-1.amzn2023.0.3.noarch                    2/8\cf1\highlight2 
\par \cf0\highlight0   Installing       : perl-lib-0.65-477.amzn2023.0.6.x86_64                        3/8\cf1\highlight2 
\par \cf0\highlight0   Installing       : perl-TermReadKey-2.38-9.amzn2023.0.2.x86_64                  4/8\cf1\highlight2 
\par \cf0\highlight0   Installing       : perl-File-Find-1.37-477.amzn2023.0.6.noarch                  5/8\cf1\highlight2 
\par \cf0\highlight0   Installing       : perl-Error-1:0.17029-5.amzn2023.0.2.noarch                   6/8\cf1\highlight2 
\par \cf0\highlight0   Installing       : perl-Git-2.40.1-1.amzn2023.0.3.noarch                        7/8\cf1\highlight2 
\par \cf0\highlight0   Installing       : git-2.40.1-1.amzn2023.0.3.x86_64                             8/8\cf1\highlight2 
\par \cf0\highlight0   Running scriptlet: git-2.40.1-1.amzn2023.0.3.x86_64                             8/8\cf1\highlight2 
\par \cf0\highlight0   Verifying        : git-2.40.1-1.amzn2023.0.3.x86_64                             1/8\cf1\highlight2 
\par \cf0\highlight0   Verifying        : git-core-2.40.1-1.amzn2023.0.3.x86_64                        2/8\cf1\highlight2 
\par \cf0\highlight0   Verifying        : git-core-doc-2.40.1-1.amzn2023.0.3.noarch                    3/8\cf1\highlight2 
\par \cf0\highlight0   Verifying        : perl-Error-1:0.17029-5.amzn2023.0.2.noarch                   4/8\cf1\highlight2 
\par \cf0\highlight0   Verifying        : perl-File-Find-1.37-477.amzn2023.0.6.noarch                  5/8\cf1\highlight2 
\par \cf0\highlight0   Verifying        : perl-Git-2.40.1-1.amzn2023.0.3.noarch                        6/8\cf1\highlight2 
\par \cf0\highlight0   Verifying        : perl-TermReadKey-2.38-9.amzn2023.0.2.x86_64                  7/8\cf1\highlight2 
\par \cf0\highlight0   Verifying        : perl-lib-0.65-477.amzn2023.0.6.x86_64                        8/8\cf1\highlight2 
\par 
\par \cf0\highlight0 Installed:\cf1\highlight2 
\par \cf0\highlight0   git-2.40.1-1.amzn2023.0.3.x86_64\cf1\highlight2 
\par \cf0\highlight0   git-core-2.40.1-1.amzn2023.0.3.x86_64\cf1\highlight2 
\par \cf0\highlight0   git-core-doc-2.40.1-1.amzn2023.0.3.noarch\cf1\highlight2 
\par \cf0\highlight0   perl-Error-1:0.17029-5.amzn2023.0.2.noarch\cf1\highlight2 
\par \cf0\highlight0   perl-File-Find-1.37-477.amzn2023.0.6.noarch\cf1\highlight2 
\par \cf0\highlight0   perl-Git-2.40.1-1.amzn2023.0.3.noarch\cf1\highlight2 
\par \cf0\highlight0   perl-TermReadKey-2.38-9.amzn2023.0.2.x86_64\cf1\highlight2 
\par \cf0\highlight0   perl-lib-0.65-477.amzn2023.0.6.x86_64\cf1\highlight2 
\par 
\par \cf0\highlight0 Complete!\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ ^C\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ git clone https://github.com/soulpage/fullstack-assignment.git\cf1\highlight2 
\par \cf0\highlight0 Cloning into 'fullstack-assignment'...\cf1\highlight2 
\par \cf0\highlight0 remote: Enumerating objects: 153, done.\cf1\highlight2 
\par \cf0\highlight0 remote: Counting objects: 100% (17/17), done.\cf1\highlight2 
\par \cf0\highlight0 remote: Compressing objects: 100% (17/17), done.\cf1\highlight2 
\par \cf0\highlight0 remote: Total 153 (delta 0), reused 0 (delta 0), pack-reused 136 (from 1)\cf1\highlight2 
\par \cf0\highlight0 Receiving objects: 100% (153/153), 392.35 KiB | 2.93 MiB/s, done.\cf1\highlight2 
\par \cf0\highlight0 Resolving deltas: 100% (12/12), done.\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ cd ~\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ ls\cf1\highlight2 
\par \cf8\highlight0 fullstack-assignment\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 ~]$ cd fullstack-assignment/\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 fullstack-assignment]$ ls\cf1\highlight2 
\par \cf0\highlight0 LICENSE  README.md  \cf8 backend\cf0   \cf8 db\cf0   \cf8 frontend\cf0   \cf8 images\cf0   \cf8 prompts\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 fullstack-assignment]$ cd backend/\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 backend]$ sudo pip3 install virtualenv\cf1\highlight2 
\par \cf0\highlight0 Collecting virtualenv\cf1\highlight2 
\par \cf0\highlight0   Downloading virtualenv-20.26.3-py3-none-any.whl (5.7 MB)\cf1\highlight2 
\par \cf0\highlight0      |\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?| 5.7 MB 6.0 MB/s\cf1\highlight2 
\par \cf0\highlight0 Collecting distlib<1,>=0.3.7\cf1\highlight2 
\par \cf0\highlight0   Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)\cf1\highlight2 
\par \cf0\highlight0      |\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?\u9608?| 468 kB 61.3 MB/s\cf1\highlight2 
\par \cf0\highlight0 Collecting filelock<4,>=3.12.2\cf1\highlight2 
\par \cf0\highlight0   Downloading filelock-3.15.4-py3-none-any.whl (16 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting platformdirs<5,>=3.9.1\cf1\highlight2 
\par \cf0\highlight0   Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)\cf1\highlight2 
\par \cf0\highlight0 Installing collected packages: platformdirs, filelock, distlib, virtualenv\cf1\highlight2 
\par \cf0\highlight0 Successfully installed distlib-0.3.8 filelock-3.15.4 platformdirs-4.2.2 virtualenv-20.26.3\cf1\highlight2 
\par \cf9\highlight0 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 backend]$ virtualenv venv\cf1\highlight2 
\par \cf0\highlight0 created virtual environment CPython3.9.16.final.0-64 in 761ms\cf1\highlight2 
\par \cf0\highlight0   creator CPython3Posix(dest=/home/ec2-user/fullstack-assignment/backend/venv, clear=False, no_vcs_ignore=False, global=False)\cf1\highlight2 
\par \cf0\highlight0   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ec2-user/.local/share/virtualenv)\cf1\highlight2 
\par \cf0\highlight0     added seed packages: pip==24.1, setuptools==70.1.0, wheel==0.43.0\cf1\highlight2 
\par \cf0\highlight0   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator\cf1\highlight2 
\par \cf0\highlight0 [ec2-user@ip-172-31-36-174 backend]$ source venv/bin/activate\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ pip install -r requirements.txt\cf1\highlight2 
\par \cf6\highlight0 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'\cf1\highlight2 
\par 
\par \cf0\highlight0\b [\cf10\b0 notice\cf0\b ]\b0  A new release of pip is available: \cf6 24.1\cf0  -> \cf11 24.2\cf1\highlight2 
\par \cf0\highlight0\b [\cf10\b0 notice\cf0\b ]\b0  To update, run: \cf11 pip install --upgrade pip\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ pip install --upgrade pip\cf1\highlight2 
\par \cf0\highlight0 Requirement already satisfied: pip in ./venv/lib/python3.9/site-packages (24.1)\cf1\highlight2 
\par \cf0\highlight0 Collecting pip\cf1\highlight2 
\par \cf0\highlight0   Using cached pip-24.2-py3-none-any.whl.metadata (3.6 kB)\cf1\highlight2 
\par \cf0\highlight0 Using cached pip-24.2-py3-none-any.whl (1.8 MB)\cf1\highlight2 
\par \cf0\highlight0 Installing collected packages: pip\cf1\highlight2 
\par \cf0\highlight0   Attempting uninstall: pip\cf1\highlight2 
\par \cf0\highlight0     Found existing installation: pip 24.1\cf1\highlight2 
\par \cf0\highlight0     Uninstalling pip-24.1:\cf1\highlight2 
\par \cf0\highlight0       Successfully uninstalled pip-24.1\cf1\highlight2 
\par \cf0\highlight0 Successfully installed pip-24.2\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ pip install python-dotenv\cf1\highlight2 
\par \cf0\highlight0 Collecting python-dotenv\cf1\highlight2 
\par \cf0\highlight0   Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)\cf1\highlight2 
\par \cf0\highlight0 Installing collected packages: python-dotenv\cf1\highlight2 
\par \cf0\highlight0 Successfully installed python-dotenv-1.0.1\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ cd ..\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 fullstack-assignment]$ cd ..\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 ~]$ ls\cf1\highlight2 
\par \cf8\highlight0 fullstack-assignment\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 ~]$ ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 ~]$ cd fullstack-assignment\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 fullstack-assignment]$ ls\cf1\highlight2 
\par \cf0\highlight0 LICENSE  README.md  \cf8 backend\cf0   \cf8 db\cf0   \cf8 frontend\cf0   \cf8 images\cf0   \cf8 prompts\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 fullstack-assignment]$ ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 fullstack-assignment]$ find . -name "manage.py"\cf1\highlight2 
\par \cf0\highlight0 ./backend/manage.py\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 fullstack-assignment]$ ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 fullstack-assignment]$ cd backend\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ls\cf1\highlight2 
\par \cf8\highlight0 authentication\cf0   \cf8 chat\cf0               \cf8 gpt\cf0         pyproject.toml  setup.py  \cf8 venv\cf1\highlight2 
\par \cf8\highlight0 backend\cf0          dependencies.txt  manage.py  server.py       \cf8 src\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$\cf1\highlight2 
\par \cf0\highlight0 nano .env\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ^[[200~ find . -name "settings.py"\cf1\highlight2 
\par \cf0\highlight0 -bash: $'\\E[200~': command not found\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ~find . -name "settings.py"\cf1\highlight2 
\par \cf0\highlight0 -bash: ~find: command not found\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ find . -name "settings.py"\cf1\highlight2 
\par \cf0\highlight0 ./backend/settings.py\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ls\cf1\highlight2 
\par \cf8\highlight0 authentication\cf0   \cf8 chat\cf0               \cf8 gpt\cf0         pyproject.toml  setup.py  \cf8 venv\cf1\highlight2 
\par \cf8\highlight0 backend\cf0          dependencies.txt  manage.py  server.py       \cf8 src\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ nano ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ nano ./backend/settings.py\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ls\cf1\highlight2 
\par \cf8\highlight0 authentication\cf0   \cf8 backend\cf0   \cf8 chat\cf0   dependencies.txt  \cf8 gpt\cf0   manage.py  pyproject.toml  serve\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ nano .env\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ python manage.py migrate\cf1\highlight2 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/manage.py", line 11, in main\cf1\highlight2 
\par \cf0\highlight0     from django.core.management import execute_from_command_line\cf1\highlight2 
\par \cf0\highlight0 ModuleNotFoundError: No module named 'django'\cf1\highlight2 
\par 
\par \cf0\highlight0 The above exception was the direct cause of the following exception:\cf1\highlight2 
\par 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/manage.py", line 22, in <module>\cf1\highlight2 
\par \cf0\highlight0     main()\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/manage.py", line 13, in main\cf1\highlight2 
\par \cf0\highlight0     raise ImportError(\cf1\highlight2 
\par \cf0\highlight0 ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ source venv/bin/activate\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ pip install django\cf1\highlight2 
\par \cf0\highlight0 Collecting django\cf1\highlight2 
\par \cf0\highlight0   Downloading Django-4.2.15-py3-none-any.whl.metadata (4.1 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting asgiref<4,>=3.6.0 (from django)\cf1\highlight2 
\par \cf0\highlight0   Downloading asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting sqlparse>=0.3.1 (from django)\cf1\highlight2 
\par \cf0\highlight0   Downloading sqlparse-0.5.1-py3-none-any.whl.metadata (3.9 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting typing-extensions>=4 (from asgiref<4,>=3.6.0->django)\cf1\highlight2 
\par \cf0\highlight0   Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading Django-4.2.15-py3-none-any.whl (8.0 MB)\cf1\highlight2 
\par \cf0\highlight0    \cf12\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\cf0  \cf11 8.0/8.0 MB\cf0  \cf6 156.1 MB/s\cf0  eta \cf7 0:00:00\cf1\highlight2 
\par \cf0\highlight0 Downloading asgiref-3.8.1-py3-none-any.whl (23 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading sqlparse-0.5.1-py3-none-any.whl (44 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)\cf1\highlight2 
\par \cf0\highlight0 Installing collected packages: typing-extensions, sqlparse, asgiref, django\cf1\highlight2 
\par \cf0\highlight0 Successfully installed asgiref-3.8.1 django-4.2.15 sqlparse-0.5.1 typing-extensions-4.12.2\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ python -m django --version\cf1\highlight2 
\par \cf0\highlight0 4.2.15\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ pip install -r requirements.txt\cf1\highlight2 
\par \cf6\highlight0 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ pip install djangorestframework\cf1\highlight2 
\par \cf0\highlight0 pip install django-cors-headers\cf1\highlight2 
\par \cf0\highlight0 pip install django-nested-admin\cf1\highlight2 
\par \cf0\highlight0 Collecting djangorestframework\cf1\highlight2 
\par \cf0\highlight0   Downloading djangorestframework-3.15.2-py3-none-any.whl.metadata (10 kB)\cf1\highlight2 
\par \cf0\highlight0 Requirement already satisfied: django>=4.2 in ./venv/lib/python3.9/site-packages (from djangorestframework) (4.2.15)\cf1\highlight2 
\par \cf0\highlight0 Requirement already satisfied: asgiref<4,>=3.6.0 in ./venv/lib/python3.9/site-packages (from django>=4.2->djangorestframework) (3.8.1)\cf1\highlight2 
\par \cf0\highlight0 Requirement already satisfied: sqlparse>=0.3.1 in ./venv/lib/python3.9/site-packages (from django>=4.2->djangorestframework) (0.5.1)\cf1\highlight2 
\par \cf0\highlight0 Requirement already satisfied: typing-extensions>=4 in ./venv/lib/python3.9/site-packages (from asgiref<4,>=3.6.0->django>=4.2->djangorestframework) (4.12.2)\cf1\highlight2 
\par \cf0\highlight0 Downloading djangorestframework-3.15.2-py3-none-any.whl (1.1 MB)\cf1\highlight2 
\par \cf0\highlight0    \cf12\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\cf0  \cf11 1.1/1.1 MB\cf0  \cf6 58.2 MB/s\cf0  eta \cf7 0:00:00\cf1\highlight2 
\par \cf0\highlight0 Installing collected packages: djangorestframework\cf1\highlight2 
\par \cf0\highlight0 Successfully installed djangorestframework-3.15.2\cf1\highlight2 
\par \cf0\highlight0 Collecting django-cors-headers\cf1\highlight2 
\par \cf0\highlight0   Downloading django_cors_headers-4.4.0-py3-none-any.whl.metadata (16 kB)\cf1\highlight2 
\par \cf0\highlight0 Requirement already satisfied: asgiref>=3.6 in ./venv/lib/python3.9/site-packages (from django-cors-headers) (3.8.1)\cf1\highlight2 
\par \cf0\highlight0 Requirement already satisfied: django>=3.2 in ./venv/lib/python3.9/site-packages (from django-cors-headers) (4.2.15)\cf1\highlight2 
\par \cf0\highlight0 Requirement already satisfied: typing-extensions>=4 in ./venv/lib/python3.9/site-packages (from asgiref>=3.6->django-cors-headers) (4.12.2)\cf1\highlight2 
\par \cf0\highlight0 Requirement already satisfied: sqlparse>=0.3.1 in ./venv/lib/python3.9/site-packages (from django>=3.2->django-cors-headers) (0.5.1)\cf1\highlight2 
\par \cf0\highlight0 Downloading django_cors_headers-4.4.0-py3-none-any.whl (12 kB)\cf1\highlight2 
\par \cf0\highlight0 Installing collected packages: django-cors-headers\cf1\highlight2 
\par \cf0\highlight0 Successfully installed django-cors-headers-4.4.0\cf1\highlight2 
\par \cf0\highlight0 Collecting django-nested-admin\cf1\highlight2 
\par \cf0\highlight0   Downloading django_nested_admin-4.1.1-py3-none-any.whl.metadata (6.4 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting python-monkey-business>=1.0.0 (from django-nested-admin)\cf1\highlight2 
\par \cf0\highlight0   Downloading python_monkey_business-1.1.0-py2.py3-none-any.whl.metadata (2.8 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading django_nested_admin-4.1.1-py3-none-any.whl (465 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading python_monkey_business-1.1.0-py2.py3-none-any.whl (4.7 kB)\cf1\highlight2 
\par \cf0\highlight0 Installing collected packages: python-monkey-business, django-nested-admin\cf1\highlight2 
\par \cf0\highlight0 Successfully installed django-nested-admin-4.1.1 python-monkey-business-1.1.0\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ pip freeze > requirements.txt\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ python -m django --version\cf1\highlight2 
\par \cf0\highlight0 4.2.15\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ python manage.py migrate\cf1\highlight2 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>\cf1\highlight2 
\par \cf0\highlight0     import psycopg as Database\cf1\highlight2 
\par \cf0\highlight0 ModuleNotFoundError: No module named 'psycopg'\cf1\highlight2 
\par 
\par \cf0\highlight0 During handling of the above exception, another exception occurred:\cf1\highlight2 
\par 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 27, in <module>\cf1\highlight2 
\par \cf0\highlight0     import psycopg2 as Database\cf1\highlight2 
\par \cf0\highlight0 ModuleNotFoundError: No module named 'psycopg2'\cf1\highlight2 
\par 
\par \cf0\highlight0 During handling of the above exception, another exception occurred:\cf1\highlight2 
\par 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/manage.py", line 22, in <module>\cf1\highlight2 
\par \cf0\highlight0     main()\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/manage.py", line 18, in main\cf1\highlight2 
\par \cf0\highlight0     execute_from_command_line(sys.argv)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line\cf1\highlight2 
\par \cf0\highlight0     utility.execute()\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 416, in execute\cf1\highlight2 
\par \cf0\highlight0     django.setup()\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup\cf1\highlight2 
\par \cf0\highlight0     apps.populate(settings.INSTALLED_APPS)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate\cf1\highlight2 
\par \cf0\highlight0     app_config.import_models()\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/apps/config.py", line 269, in import_models\cf1\highlight2 
\par \cf0\highlight0     self.models_module = import_module(models_module_name)\cf1\highlight2 
\par \cf0\highlight0   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module\cf1\highlight2 
\par \cf0\highlight0     return _bootstrap._gcd_import(name[level:], package, level)\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap_external>", line 850, in exec_module\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 3, in <module>\cf1\highlight2 
\par \cf0\highlight0     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 57, in <module>\cf1\highlight2 
\par \cf0\highlight0     class AbstractBaseUser(models.Model):\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/db/models/base.py", line 143, in __new__\cf1\highlight2 
\par \cf0\highlight0     new_class.add_to_class("_meta", Options(meta, app_label))\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/db/models/base.py", line 371, in add_to_class\cf1\highlight2 
\par \cf0\highlight0     value.contribute_to_class(cls, name)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/db/models/options.py", line 243, in contribute_to_class\cf1\highlight2 
\par \cf0\highlight0     self.db_table, connection.ops.max_name_length()\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/utils/connection.py", line 15, in __getattr__\cf1\highlight2 
\par \cf0\highlight0     return getattr(self._connections[self._alias], item)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/utils/connection.py", line 62, in __getitem__\cf1\highlight2 
\par \cf0\highlight0     conn = self.create_connection(alias)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/db/utils.py", line 193, in create_connection\cf1\highlight2 
\par \cf0\highlight0     backend = load_backend(db["ENGINE"])\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/db/utils.py", line 113, in load_backend\cf1\highlight2 
\par \cf0\highlight0     return import_module("%s.base" % backend_name)\cf1\highlight2 
\par \cf0\highlight0   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module\cf1\highlight2 
\par \cf0\highlight0     return _bootstrap._gcd_import(name[level:], package, level)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>\cf1\highlight2 
\par \cf0\highlight0     raise ImproperlyConfigured("Error loading psycopg2 or psycopg module")\cf1\highlight2 
\par \cf0\highlight0 django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 or psycopg module\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ nano ./backend/settings.py\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ pip uninstall psycopg2 psycopg2-binary\cf1\highlight2 
\par \cf9\highlight0 WARNING: Skipping psycopg2 as it is not installed.\cf1\highlight2 
\par \cf9\highlight0 WARNING: Skipping psycopg2-binary as it is not installed.\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ pip freeze > requirements.txt\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ python manage.py migrate\cf1\highlight2 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/manage.py", line 22, in <module>\cf1\highlight2 
\par \cf0\highlight0     main()\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/manage.py", line 18, in main\cf1\highlight2 
\par \cf0\highlight0     execute_from_command_line(sys.argv)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line\cf1\highlight2 
\par \cf0\highlight0     utility.execute()\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute\cf1\highlight2 
\par \cf0\highlight0     self.fetch_command(subcommand).run_from_argv(self.argv)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv\cf1\highlight2 
\par \cf0\highlight0     self.execute(*args, **cmd_options)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute\cf1\highlight2 
\par \cf0\highlight0     output = self.handle(*args, **options)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/management/base.py", line 106, in wrapper\cf1\highlight2 
\par \cf0\highlight0     res = handle_func(*args, **kwargs)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 100, in handle\cf1\highlight2 
\par \cf0\highlight0     self.check(databases=[database])\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/management/base.py", line 485, in check\cf1\highlight2 
\par \cf0\highlight0     all_issues = checks.run_checks(\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks\cf1\highlight2 
\par \cf0\highlight0     new_errors = check(app_configs=app_configs, databases=databases)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/checks/urls.py", line 14, in check_url_config\cf1\highlight2 
\par \cf0\highlight0     return check_resolver(resolver)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/checks/urls.py", line 24, in check_resolver\cf1\highlight2 
\par \cf0\highlight0     return check_method()\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 494, in check\cf1\highlight2 
\par \cf0\highlight0     for pattern in self.url_patterns:\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__\cf1\highlight2 
\par \cf0\highlight0     res = instance.__dict__[self.name] = self.func(instance)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns\cf1\highlight2 
\par \cf0\highlight0     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__\cf1\highlight2 
\par \cf0\highlight0     res = instance.__dict__[self.name] = self.func(instance)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module\cf1\highlight2 
\par \cf0\highlight0     return import_module(self.urlconf_name)\cf1\highlight2 
\par \cf0\highlight0   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module\cf1\highlight2 
\par \cf0\highlight0     return _bootstrap._gcd_import(name[level:], package, level)\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap_external>", line 850, in exec_module\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/backend/urls.py", line 17, in <module>\cf1\highlight2 
\par \cf0\highlight0     path("gpt/", include("gpt.urls")),\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include\cf1\highlight2 
\par \cf0\highlight0     urlconf_module = import_module(urlconf_module)\cf1\highlight2 
\par \cf0\highlight0   File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module\cf1\highlight2 
\par \cf0\highlight0     return _bootstrap._gcd_import(name[level:], package, level)\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap_external>", line 850, in exec_module\cf1\highlight2 
\par \cf0\highlight0   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/gpt/urls.py", line 3, in <module>\cf1\highlight2 
\par \cf0\highlight0     from gpt import views\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/gpt/views.py", line 5, in <module>\cf1\highlight2 
\par \cf0\highlight0     from src.utils.gpt import get_conversation_answer, get_gpt_title, get_simple_answer\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/src/utils/gpt.py", line 3, in <module>\cf1\highlight2 
\par \cf0\highlight0     from src.libs import openai\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/src/libs/__init__.py", line 3, in <module>\cf1\highlight2 
\par \cf0\highlight0     import openai\cf1\highlight2 
\par \cf0\highlight0 ModuleNotFoundError: No module named 'openai'\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ ^C\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ pip install openai\cf1\highlight2 
\par \cf0\highlight0 Collecting openai\cf1\highlight2 
\par \cf0\highlight0   Downloading openai-1.40.6-py3-none-any.whl.metadata (22 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting anyio<5,>=3.5.0 (from openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading anyio-4.4.0-py3-none-any.whl.metadata (4.6 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting distro<2,>=1.7.0 (from openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting httpx<1,>=0.23.0 (from openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading httpx-0.27.0-py3-none-any.whl.metadata (7.2 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting jiter<1,>=0.4.0 (from openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading jiter-0.5.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.met\cf1\highlight2 
\par \cf0\highlight0 Collecting pydantic<3,>=1.9.0 (from openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading pydantic-2.8.2-py3-none-any.whl.metadata (125 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting sniffio (from openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting tqdm>4 (from openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)\cf1\highlight2 
\par \cf0\highlight0 Requirement already satisfied: typing-extensions<5,>=4.11 in ./venv/lib/python3.9/site\cf1\highlight2 
\par \cf0\highlight0 Collecting idna>=2.8 (from anyio<5,>=3.5.0->openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading idna-3.7-py3-none-any.whl.metadata (9.9 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting exceptiongroup>=1.0.2 (from anyio<5,>=3.5.0->openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading exceptiongroup-1.2.2-py3-none-any.whl.metadata (6.6 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting certifi (from httpx<1,>=0.23.0->openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting httpcore==1.* (from httpx<1,>=0.23.0->openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading httpcore-1.0.5-py3-none-any.whl.metadata (20 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx<1,>=0.23.0->openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting annotated-types>=0.4.0 (from pydantic<3,>=1.9.0->openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)\cf1\highlight2 
\par \cf0\highlight0 Collecting pydantic-core==2.20.1 (from pydantic<3,>=1.9.0->openai)\cf1\highlight2 
\par \cf0\highlight0   Downloading pydantic_core-2.20.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_6\cf1\highlight2 
\par \cf0\highlight0 Downloading openai-1.40.6-py3-none-any.whl (361 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading anyio-4.4.0-py3-none-any.whl (86 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading distro-1.9.0-py3-none-any.whl (20 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading httpx-0.27.0-py3-none-any.whl (75 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading httpcore-1.0.5-py3-none-any.whl (77 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading jiter-0.5.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (320\cf1\highlight2 
\par \cf0\highlight0 Downloading pydantic-2.8.2-py3-none-any.whl (423 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading pydantic_core-2.20.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.\cf1\highlight2 
\par \cf0\highlight0    \cf12\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\u9473?\cf0  \cf11 2.1/2.1 MB\cf0  \cf6 96.9 MB/s\cf0  eta \cf7 0:00:00\cf1\highlight2 
\par \cf0\highlight0 Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading tqdm-4.66.5-py3-none-any.whl (78 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading exceptiongroup-1.2.2-py3-none-any.whl (16 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading idna-3.7-py3-none-any.whl (66 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading certifi-2024.7.4-py3-none-any.whl (162 kB)\cf1\highlight2 
\par \cf0\highlight0 Downloading h11-0.14.0-py3-none-any.whl (58 kB)\cf1\highlight2 
\par \cf0\highlight0 Installing collected packages: tqdm, sniffio, pydantic-core, jiter, idna, h11, excepti\cf1\highlight2 
\par \cf0\highlight0 Successfully installed annotated-types-0.7.0 anyio-4.4.0 certifi-2024.7.4 distro-1.9.0core-2.20.1 sniffio-1.3.1 tqdm-4.66.5\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ pip freeze > requirements.txt\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ nano requirements.txt\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ python manage.py migrate\cf1\highlight2 
\par \cf13\highlight0 Operations to perform:\cf1\highlight2 
\par \cf0\highlight0\b   Apply all migrations: \b0 admin, auth, authentication, chat, contenttypes, sessions\cf1\highlight2 
\par \cf13\highlight0 Running migrations:\cf1\highlight2 
\par \cf0\highlight0   Applying contenttypes.0001_initial...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying contenttypes.0002_remove_content_type_name...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying auth.0001_initial...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying auth.0002_alter_permission_name_max_length...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying auth.0003_alter_user_email_max_length...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying auth.0004_alter_user_username_opts...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying auth.0005_alter_user_last_login_null...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying auth.0006_require_contenttypes_0002...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying auth.0007_alter_validators_add_error_messages...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying auth.0008_alter_user_username_max_length...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying auth.0009_alter_user_last_name_max_length...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying auth.0010_alter_group_name_max_length...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying auth.0011_update_proxy_permissions...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying auth.0012_alter_user_first_name_max_length...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying authentication.0001_initial...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying admin.0001_initial...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying admin.0002_logentry_remove_auto_add...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying admin.0003_logentry_add_action_flag_choices...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying chat.0001_initial...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0   Applying sessions.0001_initial...\cf3  OK\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ python manage.py runserver\cf1\highlight2 
\par \cf0\highlight0 Watching for file changes with StatReloader\cf1\highlight2 
\par \cf0\highlight0 Performing system checks...\cf1\highlight2 
\par 
\par \cf0\highlight0 System check identified no issues (0 silenced).\cf1\highlight2 
\par \cf0\highlight0 August 14, 2024 - 13:39:03\cf1\highlight2 
\par \cf0\highlight0 Django version 4.2.15, using settings 'backend.settings'\cf1\highlight2 
\par \cf0\highlight0 Starting development server at http://127.0.0.1:8000/\cf1\highlight2 
\par \cf0\highlight0 Quit the server with CONTROL-C.\cf1\highlight2 
\par 
\par \cf0\highlight0 ^C(venv) [ec2-user@ip-172-31-36-174 backend]$ python manage.py runserver\cf1\highlight2 
\par \cf0\highlight0 Watching for file changes with StatReloader\cf1\highlight2 
\par \cf0\highlight0 Performing system checks...\cf1\highlight2 
\par 
\par \cf0\highlight0 System check identified no issues (0 silenced).\cf1\highlight2 
\par \cf0\highlight0 August 14, 2024 - 13:39:32\cf1\highlight2 
\par \cf0\highlight0 Django version 4.2.15, using settings 'backend.settings'\cf1\highlight2 
\par \cf0\highlight0 Starting development server at http://127.0.0.1:8000/\cf1\highlight2 
\par \cf0\highlight0 Quit the server with CONTROL-C.\cf1\highlight2 
\par 
\par \cf0\highlight0 http://127.0.0.1:8000/^C(venv) [ec2-user@ip-172-31-36-174 backend]$ python manage.py runserver\cf1\highlight2 
\par \cf0\highlight0 Watching for file changes with StatReloader\cf1\highlight2 
\par \cf0\highlight0 Performing system checks...\cf1\highlight2 
\par 
\par \cf0\highlight0 System check identified no issues (0 silenced).\cf1\highlight2 
\par \cf0\highlight0 August 14, 2024 - 13:42:41\cf1\highlight2 
\par \cf0\highlight0 Django version 4.2.15, using settings 'backend.settings'\cf1\highlight2 
\par \cf0\highlight0 Starting development server at http://127.0.0.1:8000/\cf1\highlight2 
\par \cf0\highlight0 Quit the server with CONTROL-C.\cf1\highlight2 
\par 
\par \cf0\highlight0 ^C(venv) [ec2-user@ip-172-31-36-174 backend]$ python manage.py runserver\cf1\highlight2 
\par \cf0\highlight0 Watching for file changes with StatReloader\cf1\highlight2 
\par \cf0\highlight0 Performing system checks...\cf1\highlight2 
\par 
\par \cf0\highlight0 System check identified no issues (0 silenced).\cf1\highlight2 
\par \cf0\highlight0 August 14, 2024 - 13:46:00\cf1\highlight2 
\par \cf0\highlight0 Django version 4.2.15, using settings 'backend.settings'\cf1\highlight2 
\par \cf0\highlight0 Starting development server at http://127.0.0.1:8000/\cf1\highlight2 
\par \cf0\highlight0 Quit the server with CONTROL-C.\cf1\highlight2 
\par 
\par \cf0\highlight0 ^C^C(venv) [ec2-user@ip-172-31-36-174 backenpython manage.py runserver 8080\cf14\highlight15 8080\cf1\highlight2 
\par \cf0\highlight0 Watching for file changes with StatReloader\cf1\highlight2 
\par \cf0\highlight0 Performing system checks...\cf1\highlight2 
\par 
\par \cf0\highlight0 System check identified no issues (0 silenced).\cf1\highlight2 
\par \cf0\highlight0 August 14, 2024 - 13:47:49\cf1\highlight2 
\par \cf0\highlight0 Django version 4.2.15, using settings 'backend.settings'\cf1\highlight2 
\par \cf0\highlight0 Starting development server at http://127.0.0.1:8080/\cf1\highlight2 
\par \cf0\highlight0 Quit the server with CONTROL-C.\cf1\highlight2 
\par 
\par \cf0\highlight0 ^C(venv) [ec2-user@ip-172-31-36-174 backend]$ python manage.py runserver 8080\cf1\highlight2 
\par \cf0\highlight0 Watching for file changes with StatReloader\cf1\highlight2 
\par \cf0\highlight0 Performing system checks...\cf1\highlight2 
\par 
\par \cf0\highlight0 System check identified no issues (0 silenced).\cf1\highlight2 
\par \cf0\highlight0 August 14, 2024 - 13:51:25\cf1\highlight2 
\par \cf0\highlight0 Django version 4.2.15, using settings 'backend.settings'\cf1\highlight2 
\par \cf0\highlight0 Starting development server at http://127.0.0.1:8080/\cf1\highlight2 
\par \cf0\highlight0 Quit the server with CONTROL-C.\cf1\highlight2 
\par 
\par \cf0\highlight0 ^C^C(venv) [ec2-user@ip-172-31-36-174 backenpython manage.py createsuperuser\cf14\highlight15 user\cf1\highlight2 
\par \cf0\highlight0 Email: manjunadhvarri@gmail.com\cf1\highlight2 
\par \cf0\highlight0 Password:\cf1\highlight2 
\par \cf0\highlight0 Password (again):\cf1\highlight2 
\par \cf16\highlight0 This password is too common.\cf1\highlight2 
\par \cf0\highlight0 Bypass password validation and create user anyway? [y/N]: y\cf1\highlight2 
\par \cf0\highlight0 Superuser created successfully.\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ python manage.py runserver 0.0.0.0:8000\cf1\highlight2 
\par \cf0\highlight0 Watching for file changes with StatReloader\cf1\highlight2 
\par \cf0\highlight0 Performing system checks...\cf1\highlight2 
\par 
\par \cf0\highlight0 System check identified no issues (0 silenced).\cf1\highlight2 
\par \cf0\highlight0 August 14, 2024 - 13:54:09\cf1\highlight2 
\par \cf0\highlight0 Django version 4.2.15, using settings 'backend.settings'\cf1\highlight2 
\par \cf0\highlight0 Starting development server at http://0.0.0.0:8000/\cf1\highlight2 
\par \cf0\highlight0 Quit the server with CONTROL-C.\cf1\highlight2 
\par 
\par \cf0\highlight0 Invalid HTTP_HOST header: '13.60.104.229:8000'. You may need to add '13.60.104.229' to ALLOWED_HOSTS.\cf1\highlight2 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner\cf1\highlight2 
\par \cf0\highlight0     response = get_response(request)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__\cf1\highlight2 
\par \cf0\highlight0     response = self.process_request(request)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request\cf1\highlight2 
\par \cf0\highlight0     host = request.get_host()\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host\cf1\highlight2 
\par \cf0\highlight0     raise DisallowedHost(msg)\cf1\highlight2 
\par \cf0\highlight0 django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '13.60.104.229:8000'. You may need to add '13.60.104.229' to ALLOWED_HOSTS.\cf1\highlight2 
\par \cf0\highlight0 Bad Request: /\cf1\highlight2 
\par \cf0\highlight0 [14/Aug/2024 13:54:54] \cf16 "GET / HTTP/1.1" 400 67614\cf1\highlight2 
\par \cf0\highlight0 Invalid HTTP_HOST header: '13.60.104.229:8000'. You may need to add '13.60.104.229' to ALLOWED_HOSTS.\cf1\highlight2 
\par \cf0\highlight0 Traceback (most recent call last):\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner\cf1\highlight2 
\par \cf0\highlight0     response = get_response(request)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__\cf1\highlight2 
\par \cf0\highlight0     response = self.process_request(request)\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request\cf1\highlight2 
\par \cf0\highlight0     host = request.get_host()\cf1\highlight2 
\par \cf0\highlight0   File "/home/ec2-user/fullstack-assignment/backend/venv/lib/python3.9/site-packages/django/http/request.py", line 150, in get_host\cf1\highlight2 
\par \cf0\highlight0     raise DisallowedHost(msg)\cf1\highlight2 
\par \cf0\highlight0 django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '13.60.104.229:8000'. You may need to add '13.60.104.229' to ALLOWED_HOSTS.\cf1\highlight2 
\par \cf0\highlight0 Bad Request: /favicon.ico\cf1\highlight2 
\par \cf0\highlight0 [14/Aug/2024 13:54:55] \cf16 "GET /favicon.ico HTTP/1.1" 400 67583\cf1\highlight2 
\par \cf0\highlight0 ^C(venv) [ec2-user@ip-172-31-36-174 backend]$ nano ./backend/settings.py\cf1\highlight2 
\par \cf0\highlight0 (venv) [ec2-user@ip-172-31-36-174 backend]$ python manage.py runserver 0.0.0.0:8000\cf1\highlight2 
\par \cf0\highlight0 Watching for file changes with StatReloader\cf1\highlight2 
\par \cf0\highlight0 Performing system checks...\cf1\highlight2 
\par 
\par \cf0\highlight0 System check identified no issues (0 silenced).\cf1\highlight2 
\par \cf0\highlight0 August 14, 2024 - 13:58:01\cf1\highlight2 
\par \cf0\highlight0 Django version 4.2.15, using settings 'backend.settings'\cf1\highlight2 
\par \cf0\highlight0 Starting development server at http://0.0.0.0:8000/\cf1\highlight2 
\par \cf0\highlight0 Quit the server with CONTROL-C.\cf1\highlight2 
\par 
\par \cf0\highlight0 [14/Aug/2024 13:58:04] "GET / HTTP/1.1" 200 25\cf1\highlight2 
\par \cf0\highlight0 Not Found: /favicon.ico\cf1\highlight2 
\par \cf0\highlight0 [14/Aug/2024 13:58:04] \cf9 "GET /favicon.ico HTTP/1.1" 404 2656\cf1\highlight2 
\par \cf0\highlight0 ^C(venv) [ec2-user@ip-172-31-36-174 backend]$\cf1\highlight2 
\par \pard\cf0\highlight0\f2 
\par }
 